name: execute_unit_test

# Inputs the workflow accepts.
inputs:
   path: # id of input
   required: true
   type: string

runs:
  using: "composite"

  steps:
      # Execute unit tests.
      - name: Unit tests
        if: always()
        run: gradle test

      # Generate report in GitHub action summary.
      - name: Unit test reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unit-tests
          path: ${{ inputs.path }}
          reporter: java-junit
          fail-on-error: false
