name: install_environment
description: 'Installing the environment'

# Inputs the action accepts.
inputs:
  java-ver:
    description: 'Java Version'
    required: true
  java-distribution:
    description: 'Java Distribution'
    required: true
  gradle-ver:
    description: 'Gradle Version'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set up JDK 8 for x64
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-ver }}
        distribution: ${{ inputs.java-distribution }}
        architecture: x64

    - name: Install and setup latest Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ inputs.gradle-ver }}
