name: install_environment
description: 'Installing the environment'

runs:
  using: 'composite'

  steps:


    - name: Set up JDK 8 for x64
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        architecture: x64

    - name: Install and setup latest Google Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.9
